[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.23"

remappings = [
    "@semaphore-protocol/contracts/=lib/semaphore/packages/contracts/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
]
